/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UslugiRouteImport } from './routes/uslugi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProizvodstvoRouteImport } from './routes/proizvodstvo'
import { Route as ProektyRouteImport } from './routes/proekty'
import { Route as PontonyDlyaScenyRouteImport } from './routes/pontony-dlya-sceny'
import { Route as PontonyDlyaSadkovRouteImport } from './routes/pontony-dlya-sadkov'
import { Route as PontonyDlyaRestoranaRouteImport } from './routes/pontony-dlya-restorana'
import { Route as PontonyDlyaKaterovRouteImport } from './routes/pontony-dlya-katerov'
import { Route as PontonyDlyaHausbotaRouteImport } from './routes/pontony-dlya-hausbota'
import { Route as PontonyDlyaBesedkiRouteImport } from './routes/pontony-dlya-besedki'
import { Route as PontonyDlyaBaniRouteImport } from './routes/pontony-dlya-bani'
import { Route as PlavuchieKonstrukciiRouteImport } from './routes/plavuchie-konstrukcii'
import { Route as PlavuchieGarazhiEllingiRouteImport } from './routes/plavuchie-garazhi-ellingi'
import { Route as PirsyPrichalyRouteImport } from './routes/pirsy-prichaly'
import { Route as OtzyvyRouteImport } from './routes/otzyvy'
import { Route as OKompaniiRouteImport } from './routes/o-kompanii'
import { Route as KontaktyRouteImport } from './routes/kontakty'
import { Route as KalkulyatorRouteImport } from './routes/kalkulyator'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'

const UslugiRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProizvodstvoRoute = ProizvodstvoRouteImport.update({
  id: '/proizvodstvo',
  path: '/proizvodstvo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProektyRoute = ProektyRouteImport.update({
  id: '/proekty',
  path: '/proekty',
  getParentRoute: () => rootRouteImport,
} as any)
const PontonyDlyaScenyRoute = PontonyDlyaScenyRouteImport.update({
  id: '/pontony-dlya-sceny',
  path: '/pontony-dlya-sceny',
  getParentRoute: () => rootRouteImport,
} as any)
const PontonyDlyaSadkovRoute = PontonyDlyaSadkovRouteImport.update({
  id: '/pontony-dlya-sadkov',
  path: '/pontony-dlya-sadkov',
  getParentRoute: () => rootRouteImport,
} as any)
const PontonyDlyaRestoranaRoute = PontonyDlyaRestoranaRouteImport.update({
  id: '/pontony-dlya-restorana',
  path: '/pontony-dlya-restorana',
  getParentRoute: () => rootRouteImport,
} as any)
const PontonyDlyaKaterovRoute = PontonyDlyaKaterovRouteImport.update({
  id: '/pontony-dlya-katerov',
  path: '/pontony-dlya-katerov',
  getParentRoute: () => rootRouteImport,
} as any)
const PontonyDlyaHausbotaRoute = PontonyDlyaHausbotaRouteImport.update({
  id: '/pontony-dlya-hausbota',
  path: '/pontony-dlya-hausbota',
  getParentRoute: () => rootRouteImport,
} as any)
const PontonyDlyaBesedkiRoute = PontonyDlyaBesedkiRouteImport.update({
  id: '/pontony-dlya-besedki',
  path: '/pontony-dlya-besedki',
  getParentRoute: () => rootRouteImport,
} as any)
const PontonyDlyaBaniRoute = PontonyDlyaBaniRouteImport.update({
  id: '/pontony-dlya-bani',
  path: '/pontony-dlya-bani',
  getParentRoute: () => rootRouteImport,
} as any)
const PlavuchieKonstrukciiRoute = PlavuchieKonstrukciiRouteImport.update({
  id: '/plavuchie-konstrukcii',
  path: '/plavuchie-konstrukcii',
  getParentRoute: () => rootRouteImport,
} as any)
const PlavuchieGarazhiEllingiRoute = PlavuchieGarazhiEllingiRouteImport.update({
  id: '/plavuchie-garazhi-ellingi',
  path: '/plavuchie-garazhi-ellingi',
  getParentRoute: () => rootRouteImport,
} as any)
const PirsyPrichalyRoute = PirsyPrichalyRouteImport.update({
  id: '/pirsy-prichaly',
  path: '/pirsy-prichaly',
  getParentRoute: () => rootRouteImport,
} as any)
const OtzyvyRoute = OtzyvyRouteImport.update({
  id: '/otzyvy',
  path: '/otzyvy',
  getParentRoute: () => rootRouteImport,
} as any)
const OKompaniiRoute = OKompaniiRouteImport.update({
  id: '/o-kompanii',
  path: '/o-kompanii',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktyRoute = KontaktyRouteImport.update({
  id: '/kontakty',
  path: '/kontakty',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulyatorRoute = KalkulyatorRouteImport.update({
  id: '/kalkulyator',
  path: '/kalkulyator',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/blog': typeof BlogRoute
  '/faq': typeof FaqRoute
  '/kalkulyator': typeof KalkulyatorRoute
  '/kontakty': typeof KontaktyRoute
  '/o-kompanii': typeof OKompaniiRoute
  '/otzyvy': typeof OtzyvyRoute
  '/pirsy-prichaly': typeof PirsyPrichalyRoute
  '/plavuchie-garazhi-ellingi': typeof PlavuchieGarazhiEllingiRoute
  '/plavuchie-konstrukcii': typeof PlavuchieKonstrukciiRoute
  '/pontony-dlya-bani': typeof PontonyDlyaBaniRoute
  '/pontony-dlya-besedki': typeof PontonyDlyaBesedkiRoute
  '/pontony-dlya-hausbota': typeof PontonyDlyaHausbotaRoute
  '/pontony-dlya-katerov': typeof PontonyDlyaKaterovRoute
  '/pontony-dlya-restorana': typeof PontonyDlyaRestoranaRoute
  '/pontony-dlya-sadkov': typeof PontonyDlyaSadkovRoute
  '/pontony-dlya-sceny': typeof PontonyDlyaScenyRoute
  '/proekty': typeof ProektyRoute
  '/proizvodstvo': typeof ProizvodstvoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/blog': typeof BlogRoute
  '/faq': typeof FaqRoute
  '/kalkulyator': typeof KalkulyatorRoute
  '/kontakty': typeof KontaktyRoute
  '/o-kompanii': typeof OKompaniiRoute
  '/otzyvy': typeof OtzyvyRoute
  '/pirsy-prichaly': typeof PirsyPrichalyRoute
  '/plavuchie-garazhi-ellingi': typeof PlavuchieGarazhiEllingiRoute
  '/plavuchie-konstrukcii': typeof PlavuchieKonstrukciiRoute
  '/pontony-dlya-bani': typeof PontonyDlyaBaniRoute
  '/pontony-dlya-besedki': typeof PontonyDlyaBesedkiRoute
  '/pontony-dlya-hausbota': typeof PontonyDlyaHausbotaRoute
  '/pontony-dlya-katerov': typeof PontonyDlyaKaterovRoute
  '/pontony-dlya-restorana': typeof PontonyDlyaRestoranaRoute
  '/pontony-dlya-sadkov': typeof PontonyDlyaSadkovRoute
  '/pontony-dlya-sceny': typeof PontonyDlyaScenyRoute
  '/proekty': typeof ProektyRoute
  '/proizvodstvo': typeof ProizvodstvoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/blog': typeof BlogRoute
  '/faq': typeof FaqRoute
  '/kalkulyator': typeof KalkulyatorRoute
  '/kontakty': typeof KontaktyRoute
  '/o-kompanii': typeof OKompaniiRoute
  '/otzyvy': typeof OtzyvyRoute
  '/pirsy-prichaly': typeof PirsyPrichalyRoute
  '/plavuchie-garazhi-ellingi': typeof PlavuchieGarazhiEllingiRoute
  '/plavuchie-konstrukcii': typeof PlavuchieKonstrukciiRoute
  '/pontony-dlya-bani': typeof PontonyDlyaBaniRoute
  '/pontony-dlya-besedki': typeof PontonyDlyaBesedkiRoute
  '/pontony-dlya-hausbota': typeof PontonyDlyaHausbotaRoute
  '/pontony-dlya-katerov': typeof PontonyDlyaKaterovRoute
  '/pontony-dlya-restorana': typeof PontonyDlyaRestoranaRoute
  '/pontony-dlya-sadkov': typeof PontonyDlyaSadkovRoute
  '/pontony-dlya-sceny': typeof PontonyDlyaScenyRoute
  '/proekty': typeof ProektyRoute
  '/proizvodstvo': typeof ProizvodstvoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslugi': typeof UslugiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/blog'
    | '/faq'
    | '/kalkulyator'
    | '/kontakty'
    | '/o-kompanii'
    | '/otzyvy'
    | '/pirsy-prichaly'
    | '/plavuchie-garazhi-ellingi'
    | '/plavuchie-konstrukcii'
    | '/pontony-dlya-bani'
    | '/pontony-dlya-besedki'
    | '/pontony-dlya-hausbota'
    | '/pontony-dlya-katerov'
    | '/pontony-dlya-restorana'
    | '/pontony-dlya-sadkov'
    | '/pontony-dlya-sceny'
    | '/proekty'
    | '/proizvodstvo'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/uslugi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/blog'
    | '/faq'
    | '/kalkulyator'
    | '/kontakty'
    | '/o-kompanii'
    | '/otzyvy'
    | '/pirsy-prichaly'
    | '/plavuchie-garazhi-ellingi'
    | '/plavuchie-konstrukcii'
    | '/pontony-dlya-bani'
    | '/pontony-dlya-besedki'
    | '/pontony-dlya-hausbota'
    | '/pontony-dlya-katerov'
    | '/pontony-dlya-restorana'
    | '/pontony-dlya-sadkov'
    | '/pontony-dlya-sceny'
    | '/proekty'
    | '/proizvodstvo'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/uslugi'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/blog'
    | '/faq'
    | '/kalkulyator'
    | '/kontakty'
    | '/o-kompanii'
    | '/otzyvy'
    | '/pirsy-prichaly'
    | '/plavuchie-garazhi-ellingi'
    | '/plavuchie-konstrukcii'
    | '/pontony-dlya-bani'
    | '/pontony-dlya-besedki'
    | '/pontony-dlya-hausbota'
    | '/pontony-dlya-katerov'
    | '/pontony-dlya-restorana'
    | '/pontony-dlya-sadkov'
    | '/pontony-dlya-sceny'
    | '/proekty'
    | '/proizvodstvo'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/uslugi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BlogRoute: typeof BlogRoute
  FaqRoute: typeof FaqRoute
  KalkulyatorRoute: typeof KalkulyatorRoute
  KontaktyRoute: typeof KontaktyRoute
  OKompaniiRoute: typeof OKompaniiRoute
  OtzyvyRoute: typeof OtzyvyRoute
  PirsyPrichalyRoute: typeof PirsyPrichalyRoute
  PlavuchieGarazhiEllingiRoute: typeof PlavuchieGarazhiEllingiRoute
  PlavuchieKonstrukciiRoute: typeof PlavuchieKonstrukciiRoute
  PontonyDlyaBaniRoute: typeof PontonyDlyaBaniRoute
  PontonyDlyaBesedkiRoute: typeof PontonyDlyaBesedkiRoute
  PontonyDlyaHausbotaRoute: typeof PontonyDlyaHausbotaRoute
  PontonyDlyaKaterovRoute: typeof PontonyDlyaKaterovRoute
  PontonyDlyaRestoranaRoute: typeof PontonyDlyaRestoranaRoute
  PontonyDlyaSadkovRoute: typeof PontonyDlyaSadkovRoute
  PontonyDlyaScenyRoute: typeof PontonyDlyaScenyRoute
  ProektyRoute: typeof ProektyRoute
  ProizvodstvoRoute: typeof ProizvodstvoRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UslugiRoute: typeof UslugiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proizvodstvo': {
      id: '/proizvodstvo'
      path: '/proizvodstvo'
      fullPath: '/proizvodstvo'
      preLoaderRoute: typeof ProizvodstvoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proekty': {
      id: '/proekty'
      path: '/proekty'
      fullPath: '/proekty'
      preLoaderRoute: typeof ProektyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pontony-dlya-sceny': {
      id: '/pontony-dlya-sceny'
      path: '/pontony-dlya-sceny'
      fullPath: '/pontony-dlya-sceny'
      preLoaderRoute: typeof PontonyDlyaScenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pontony-dlya-sadkov': {
      id: '/pontony-dlya-sadkov'
      path: '/pontony-dlya-sadkov'
      fullPath: '/pontony-dlya-sadkov'
      preLoaderRoute: typeof PontonyDlyaSadkovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pontony-dlya-restorana': {
      id: '/pontony-dlya-restorana'
      path: '/pontony-dlya-restorana'
      fullPath: '/pontony-dlya-restorana'
      preLoaderRoute: typeof PontonyDlyaRestoranaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pontony-dlya-katerov': {
      id: '/pontony-dlya-katerov'
      path: '/pontony-dlya-katerov'
      fullPath: '/pontony-dlya-katerov'
      preLoaderRoute: typeof PontonyDlyaKaterovRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pontony-dlya-hausbota': {
      id: '/pontony-dlya-hausbota'
      path: '/pontony-dlya-hausbota'
      fullPath: '/pontony-dlya-hausbota'
      preLoaderRoute: typeof PontonyDlyaHausbotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pontony-dlya-besedki': {
      id: '/pontony-dlya-besedki'
      path: '/pontony-dlya-besedki'
      fullPath: '/pontony-dlya-besedki'
      preLoaderRoute: typeof PontonyDlyaBesedkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pontony-dlya-bani': {
      id: '/pontony-dlya-bani'
      path: '/pontony-dlya-bani'
      fullPath: '/pontony-dlya-bani'
      preLoaderRoute: typeof PontonyDlyaBaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plavuchie-konstrukcii': {
      id: '/plavuchie-konstrukcii'
      path: '/plavuchie-konstrukcii'
      fullPath: '/plavuchie-konstrukcii'
      preLoaderRoute: typeof PlavuchieKonstrukciiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plavuchie-garazhi-ellingi': {
      id: '/plavuchie-garazhi-ellingi'
      path: '/plavuchie-garazhi-ellingi'
      fullPath: '/plavuchie-garazhi-ellingi'
      preLoaderRoute: typeof PlavuchieGarazhiEllingiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pirsy-prichaly': {
      id: '/pirsy-prichaly'
      path: '/pirsy-prichaly'
      fullPath: '/pirsy-prichaly'
      preLoaderRoute: typeof PirsyPrichalyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otzyvy': {
      id: '/otzyvy'
      path: '/otzyvy'
      fullPath: '/otzyvy'
      preLoaderRoute: typeof OtzyvyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-kompanii': {
      id: '/o-kompanii'
      path: '/o-kompanii'
      fullPath: '/o-kompanii'
      preLoaderRoute: typeof OKompaniiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakty': {
      id: '/kontakty'
      path: '/kontakty'
      fullPath: '/kontakty'
      preLoaderRoute: typeof KontaktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulyator': {
      id: '/kalkulyator'
      path: '/kalkulyator'
      fullPath: '/kalkulyator'
      preLoaderRoute: typeof KalkulyatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BlogRoute: BlogRoute,
  FaqRoute: FaqRoute,
  KalkulyatorRoute: KalkulyatorRoute,
  KontaktyRoute: KontaktyRoute,
  OKompaniiRoute: OKompaniiRoute,
  OtzyvyRoute: OtzyvyRoute,
  PirsyPrichalyRoute: PirsyPrichalyRoute,
  PlavuchieGarazhiEllingiRoute: PlavuchieGarazhiEllingiRoute,
  PlavuchieKonstrukciiRoute: PlavuchieKonstrukciiRoute,
  PontonyDlyaBaniRoute: PontonyDlyaBaniRoute,
  PontonyDlyaBesedkiRoute: PontonyDlyaBesedkiRoute,
  PontonyDlyaHausbotaRoute: PontonyDlyaHausbotaRoute,
  PontonyDlyaKaterovRoute: PontonyDlyaKaterovRoute,
  PontonyDlyaRestoranaRoute: PontonyDlyaRestoranaRoute,
  PontonyDlyaSadkovRoute: PontonyDlyaSadkovRoute,
  PontonyDlyaScenyRoute: PontonyDlyaScenyRoute,
  ProektyRoute: ProektyRoute,
  ProizvodstvoRoute: ProizvodstvoRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UslugiRoute: UslugiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
